### ISSUE TITLE
What effects should the soul types have?

### ISSUE THREAD

**Issue by Aelpecyem** [Aelpecyem/Elementaristics#1]
> COMMON SOULS:
-Air Soul ("The air swirls and I swirl with it...  and the harmony persists")
-Fire Soul ("The fire roars and so does my soul... and shall burn forever")
-Water Soul ("The water flows, the water feels... and the water feels me")
-Earth Soul ("The heart moves, the world moves... and I am the center")
-Aether Soul ("The space screams, the space whispers... we are all stardust but I am a star")
-Magan Soul ("The fabric was stitched and so was I... and I am a masterpiece")

> RARE SOULS:
-Mana Soul ("The Fabric was stitched... but I was the string")
-Immutable Soul ("I persisted... and I will persist")
-Instable Soul ("My walls hold my sanity in, but keep the knowledge out... and my walls crumble")
-Balanced Soul ("I am me... not the true me, but less of a lie")

> LEGENDARY SOULS:
-Dragon Soul ("Dragons don't roar, dragons sing... and the world shall hear my song")
-Ancient Soul ("The Old Ones sleep... but I have awoken")

These are the "descriptions" of the souls. Just come with any ideas you want.

**Comment by Enderborn1235** [comment]
A couple of Soul Ideas(idk what to do with them):
Greater Legendary
-Artificial(or Alchemical) Soul("I was not born... I was built"): endgame DIY-style soul for the aspiring Lich. It would be rare to start with, but later could be easily built or modified, with the right research.
Variant type(Same Soul name, different Features, rare even among legendary rarity):
-Parasitic: Replace 'I' with 'we' in descriptions. Could offer x number increase compared to normal, It would probably be found rarely in Slimes and/or Magma Cubes, and it would "latch" itself onto your soul. It unlatches upon player death, to find new a "host". It could provide dialogue on certain events.

**Comment by Aelpecyem** [comment]
Interesting, though I'll probably not add them for now (maybe as ascended souls).
Either way, I'll only add them after the first full release, if even.

**Comment by Enderborn1235** [comment]
Sounds Cool!
