### ISSUE TITLE
[Fixed] Crash when loading game with Botania

### ISSUE THREAD

**Issue by EpicSquid** [Aelpecyem/Elementaristics#2]
Crash due to loottable injection issue. I am very keen to use this mod, so hope you get a chance to fix this asap. Also, hit me up on Discord if your on there, I would be keen to chat :D

https://paste.dimdev.org/aruwofonew.sql

**Comment by Aelpecyem** [comment]
k, the new build has been pushed to github.
I will release a new build on curseforge soon, though it may contain other content that is not quite functional yet.
