### ISSUE TITLE
Tunneling problem

### ISSUE THREAD

**Issue by Zack7292** [Aelpecyem/Elementaristics#4]
hi, i try to do tunneling while testing this mod, i actually didn't understand it, i put everything and waqit for a long time, i reput stuff again and agian, maybe telling in the boook how many time each tunneling ritual take could be useful?

**Comment by Aelpecyem** [comment]
you need to activate the block with a redstone signal

**Comment by Zack7292** [comment]
oooohhhh.... i think it should be precise (and if it is, be put in red or a color) tath to do tunneling you need redstone signal

**Comment by Aelpecyem** [comment]
(in the rewrite, probably, but for now Elem's kinda gonna be a 1.12.2 orphan lol)
