### ISSUE TITLE
a crahs with the latest version

### ISSUE THREAD

**Issue by Zack7292** [Aelpecyem/Elementaristics#5]
hi i crash with your mod and few other, for vanillaFix, its cause by yours, so there's my crahs log (mod list include)
https://paste.dimdev.org/yuvetafeze.mccrash

**Comment by Zack7292** [comment]
this occur while launching minecraft in the 3 last section (i don't exacly know i wasn't looking but i know it passed the 3rd one)  and this also dosn't occur with 0.0.9.6.1 but it occur with 0.0.9.6.2

**Comment by Sunconure11** [comment]
I'm having a similar crash.

https://paste.dimdev.org/mutarereho.mccrash

**Comment by Aelpecyem** [comment]
this _should_ be fixed now, a new build should also appear on curseforge soon

**Comment by Zack7292** [comment]
thank you very mush tho!, you fix it really faST!

**Comment by Aelpecyem** [comment]
I also pushed an additional build fixing another bug
